namespace DALib.Enums;

/// <summary>
///     Body animation / emote identifier. Byte values match the retail wire encoding.
///     0-44 are emotes/expressions; 128+ are combat and casting animations. Gaps are
///     intentional (unused IDs in the retail set).
/// </summary>
#pragma warning disable CS1591 // self-evident emote/animation names; per-member docs would be noise
public enum BodyAnimation : byte
{
    None = 0,
    Assail = 1,
    HandsUp = 6,
    Smile = 9,
    Cry = 10,
    Frown = 11,
    Wink = 12,
    Surprise = 13,
    Tongue = 14,
    Pleasant = 15,
    Snore = 16,
    Mouth = 17,
    BlowKiss = 21,
    Wave = 22,
    RockOn = 23,
    Peace = 24,
    Stop = 25,
    Ouch = 26,
    Impatient = 27,
    Shock = 28,
    Pleasure = 29,
    Love = 30,
    SweatDrop = 31,
    Whistle = 32,
    Irritation = 33,
    Silly = 34,
    Cute = 35,
    Yelling = 36,
    Mischievous = 37,
    Evil = 38,
    Horror = 39,
    PuppyDog = 40,
    StoneFaced = 41,
    Tears = 42,
    FiredUp = 43,
    Confused = 44,
    PriestCast = 128,
    TwoHandAtk = 129,
    Jump = 130,
    Kick = 131,
    Punch = 132,
    RoundHouseKick = 133,
    Stab = 134,
    DoubleStab = 135,
    WizardCast = 136,
    PlayNotes = 137,
    HandsUp2 = 138,
    Swipe = 139,
    HeavySwipe = 140,
    JumpAttack = 141,
    BowShot = 142,
    HeavyBowShot = 143,
    LongBowShot = 144,
    Summon = 145
}
